/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanresourcesystemm;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;







/**
 *
 * @author husss
 */
public class deductions extends javax.swing.JFrame {

    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    
    
    /**
     * Creates new form deductions
     */
    public deductions() {
        initComponents();
        
//        conn=db.db_java();
         
              this.setSize(792, 526); 
this.setLocationRelativeTo(null); 
this.setResizable(false); 
         
         
         lbl_emp.setText(String.valueOf(Emp.empId).toString());

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_job = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_dep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_desig = new javax.swing.JTextField();
        txt_empid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        r_percentage = new javax.swing.JRadioButton();
        r_amount = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txt_percentage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lbl_sal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_reason = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt_job);
        txt_job.setBounds(417, 160, 131, 22);

        jLabel11.setText("Status");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(357, 203, 33, 16);
        getContentPane().add(txt_status);
        txt_status.setBounds(417, 200, 131, 22);

        jLabel5.setText("Last Name:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 163, 58, 16);
        getContentPane().add(txt_lastname);
        txt_lastname.setBounds(82, 160, 131, 22);

        label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label.setText("Deductions:");
        getContentPane().add(label);
        label.setBounds(433, 271, 78, 20);

        jLabel6.setText("Date of Birth:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 203, 69, 16);
        getContentPane().add(txt_dob);
        txt_dob.setBounds(81, 200, 131, 22);

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_total.setText("0.00");
        getContentPane().add(lbl_total);
        lbl_total.setBounds(523, 271, 28, 20);

        jLabel7.setText("Basic Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 243, 61, 16);
        getContentPane().add(txt_salary);
        txt_salary.setBounds(73, 240, 131, 22);

        jLabel8.setText("Department");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(6, 283, 63, 16);
        getContentPane().add(txt_dep);
        txt_dep.setBounds(75, 280, 131, 22);

        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 42, 70, 16);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(85, 39, 519, 22);

        jLabel4.setText("Designation");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 83, 63, 16);

        jLabel2.setText("Employee ID: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 83, 73, 16);
        getContentPane().add(txt_desig);
        txt_desig.setBounds(419, 80, 128, 22);
        getContentPane().add(txt_empid);
        txt_empid.setBounds(85, 80, 129, 22);

        jLabel9.setText("Date Hired");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 123, 61, 16);

        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 123, 59, 16);
        getContentPane().add(txt_doj);
        txt_doj.setBounds(417, 120, 131, 22);
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(83, 120, 131, 22);

        jLabel10.setText("Job Title");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 163, 43, 16);

        jLabel14.setText("Update Salary By: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(75, 329, 95, 16);

        r_percentage.setText("Percentage%");
        r_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_percentageActionPerformed(evt);
            }
        });
        getContentPane().add(r_percentage);
        r_percentage.setBounds(176, 327, 91, 21);

        r_amount.setText("Amount");
        r_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amountActionPerformed(evt);
            }
        });
        getContentPane().add(r_amount);
        r_amount.setBounds(273, 327, 66, 21);

        jLabel15.setText("Percentage");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(75, 366, 58, 16);

        txt_percentage.setEditable(false);
        getContentPane().add(txt_percentage);
        txt_percentage.setBounds(139, 363, 71, 22);

        jLabel16.setText("Amount");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(216, 366, 43, 16);

        txt_amount.setEditable(false);
        getContentPane().add(txt_amount);
        txt_amount.setBounds(277, 363, 71, 22);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Salary After Deduction:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(433, 321, 153, 20);

        lbl_sal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_sal.setText("0.00");
        getContentPane().add(lbl_sal);
        lbl_sal.setBounds(592, 321, 28, 20);

        jLabel19.setText("Reason:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(75, 400, 41, 16);
        getContentPane().add(txt_reason);
        txt_reason.setBounds(122, 397, 446, 22);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(148, 431, 72, 31);

        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(267, 431, 77, 31);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(391, 431, 72, 31);

        jLabel20.setText("Logged in As ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(6, 478, 73, 16);

        lbl_emp.setText("emp");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(85, 478, 24, 16);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ChatGPT Image Jun 6, 2025, 01_27_06 PM.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 790, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
          try{

            String sql ="select * from Staff_information where id=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("id");
            txt_empid.setText(add1);

            String add2 =rs.getString("first_name");
            txt_firstname.setText(add2);

            String add3 =rs.getString("last_name");
            txt_lastname.setText(add3);

            String add4 =rs.getString("Dob");
            txt_dob.setText(add4);

            String add5 =rs.getString("Department");
            txt_dep.setText(add5);

            String add7 =rs.getString("Salary");
            txt_salary.setText(add7);

            String add8 =rs.getString("Status");
            txt_status.setText(add8);

            String add9 =rs.getString("Date_hired");
            txt_doj.setText(add9);

            String add10 =rs.getString("job_title");
            txt_job.setText(add10);

            String add17 =rs.getString("Designation");
            txt_desig.setText(add17);

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(SQLException e){

            }
        }

        

       

    }//GEN-LAST:event_txt_searchKeyReleased

    private void r_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_percentageActionPerformed
        // TODO add your handling code here:
       

        r_percentage.setSelected(true);
        r_amount.setSelected(false);
        //r_amount.setEnabled(false);
        txt_amount.setEnabled(false);
        txt_percentage.setEditable(true);
        txt_percentage.setEnabled(true);
        txt_amount.setText("");

    }//GEN-LAST:event_r_percentageActionPerformed

    private void r_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amountActionPerformed
        // TODO add your handling code here:

        r_amount.setSelected(true);
        r_percentage.setSelected(false);
        //r_percentage.setEnabled(false);
        txt_percentage.setEnabled(false);
        txt_amount.setEditable(true);
        txt_amount.setEnabled(true);
        txt_percentage.setText("");

    }//GEN-LAST:event_r_amountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){

              String value3 = lbl_emp.getText();
            try {

                String sql ="insert into Deductions (firstname,surname,salary,deduction_amount,deduction_reason,emp_id,made_by) values (?,?,?,?,?,?,'"+value3+"')";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_firstname.getText());
                pst.setString(2,txt_lastname.getText());
                pst.setString(3,txt_salary.getText());
                pst.setString(4,lbl_total.getText());
                pst.setString(5,txt_reason.getText());
                pst.setString(6,txt_empid.getText());
  
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }
            catch (HeadlessException | SQLException e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
           
         finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
                }
            }
        }

        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
         int salary = Integer.parseInt(txt_salary.getText());
        
         if(r_percentage.isSelected()== true){
        int percentage = Integer.parseInt(txt_percentage.getText());
        //calculate the total hours of overtime
        int total_percentage_deduction = salary /100 * percentage;
        String x = String.valueOf(total_percentage_deduction);
        int sal = salary - total_percentage_deduction;
        lbl_total.setText(x);
        lbl_sal.setText(String.valueOf(sal));
         }
        
        if(r_amount.isSelected()== true){
        int deduction = Integer.parseInt(txt_amount.getText());
        //calculate the total hours of overtime
        int total_amount_deduction =  salary - deduction;
        String s = String.valueOf(total_amount_deduction);
       
        lbl_sal.setText(s);
        lbl_total.setText(String.valueOf(deduction));

}



        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txt_empid.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_dob.setText("");
        txt_dep.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_desig.setText("");
        txt_job.setText("");
        txt_doj.setText("");
        lbl_total.setText("0.00");
        txt_percentage.setText("");
        txt_amount.setText("");
        txt_reason.setText("");
        txt_search.setText("");
        lbl_sal.setText("0.00");

        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deductions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_sal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JRadioButton r_amount;
    private javax.swing.JRadioButton r_percentage;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_desig;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_reason;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
