/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanresourcesystemm;

import java.io.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author husss
 */
public class addEmployee extends javax.swing.JFrame {

 Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;   
    private String gender;
    
    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
         conn=db.db_java();
       this.setSize(792, 526); 
this.setLocationRelativeTo(null); 
this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_add1 = new javax.swing.JTextField();
        txt_add2 = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        txt_doj = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        txt_apt = new javax.swing.JTextField();
        txt_pc = new javax.swing.JTextField();
        txt_dep = new javax.swing.JTextField();
        txt_design = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("First Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(95, 121, 82, 24);

        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(95, 91, 82, 24);

        jLabel3.setText("Date of Birth");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(95, 212, 82, 24);

        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(95, 149, 82, 24);

        jLabel5.setText("Temporary Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(95, 308, 104, 24);

        jLabel6.setText("Permanent Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(95, 338, 115, 24);

        jLabel7.setText("Contact");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(95, 272, 74, 24);

        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(95, 242, 74, 24);

        jLabel9.setText("Date Hired");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(334, 251, 70, 24);

        jLabel10.setText("Post Code");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(334, 160, 70, 24);

        jLabel11.setText("House No.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(334, 130, 70, 24);

        jLabel12.setText("Designation");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(334, 217, 70, 24);

        jLabel13.setText("Department");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(334, 188, 70, 24);

        jLabel14.setText("Job Title ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(334, 91, 70, 24);

        jLabel15.setText("Status");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(334, 338, 70, 24);

        jLabel16.setText("Basic Salary");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(334, 278, 70, 24);

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(234, 92, 71, 22);
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(234, 122, 71, 22);
        getContentPane().add(txt_lastname);
        txt_lastname.setBounds(234, 150, 71, 22);
        getContentPane().add(txt_dob);
        txt_dob.setBounds(221, 213, 84, 22);
        getContentPane().add(txt_email);
        txt_email.setBounds(221, 243, 84, 22);

        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contact);
        txt_contact.setBounds(221, 273, 84, 22);
        getContentPane().add(txt_add1);
        txt_add1.setBounds(228, 309, 98, 22);
        getContentPane().add(txt_add2);
        txt_add2.setBounds(234, 339, 71, 22);
        getContentPane().add(txt_status);
        txt_status.setBounds(410, 339, 71, 22);
        getContentPane().add(txt_doj);
        txt_doj.setBounds(410, 252, 71, 22);
        getContentPane().add(txt_salary);
        txt_salary.setBounds(410, 279, 71, 22);
        getContentPane().add(txt_job);
        txt_job.setBounds(410, 92, 71, 22);
        getContentPane().add(txt_apt);
        txt_apt.setBounds(410, 122, 71, 22);
        getContentPane().add(txt_pc);
        txt_pc.setBounds(410, 150, 71, 22);
        getContentPane().add(txt_dep);
        txt_dep.setBounds(410, 178, 71, 22);
        getContentPane().add(txt_design);
        txt_design.setBounds(410, 218, 71, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Save-icon.png"))); // NOI18N
        jButton1.setText("Add Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 400, 112, 39);

        jLabel17.setText("Gender");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(95, 181, 38, 16);

        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        getContentPane().add(r_male);
        r_male.setBounds(181, 179, 48, 21);

        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(r_female);
        r_female.setBounds(235, 179, 60, 21);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/erase-128.png"))); // NOI18N
        jButton2.setText("Clear all");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 400, 92, 39);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/attachment-512.png"))); // NOI18N
        jButton3.setText("Add img");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 400, 120, 39);

        jLabel18.setText("Search Employee");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(113, 66, 90, 16);

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(221, 63, 311, 22);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/delete_16x16.gif"))); // NOI18N
        jButton4.setText("Delete Employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(620, 400, 160, 39);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/update icon.png"))); // NOI18N
        jButton5.setText("Update Data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 400, 140, 39);

        img.setText("                ");

        jDesktopPane2.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(550, 110, 201, 172);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("                                       Employee Details");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(113, 12, 368, 33);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ChatGPT Image Jun 6, 2025, 01_17_34 PM.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){ 
          try  { 
              String sql = "INSERT INTO Staff_information (" +
    "first_name, last_name, Dob, Email, " +
    "Telephone, Address, Department, " +
    "Image, Salary, Gender, Address2, " +
    "Post_code, Designation, Status, job_title, Apartment, Date_hired" +
    ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                

                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_firstname.getText());
                pst.setString(2,txt_lastname.getText());
                pst.setString(3,txt_dob.getText());
                pst.setString(4,txt_email.getText());
                pst.setString(5,txt_contact.getText());
                pst.setString(6,txt_add1.getText());
                pst.setString(7,txt_dep.getText());
                pst.setBytes(8, person_image);
      

                pst.setString(9,txt_salary.getText());
                pst.setString(10, gender);
     
                pst.setString(11,txt_add2.getText());
                pst.setString(12,txt_pc.getText());
                pst.setString(13,txt_design.getText());
                pst.setString(14,txt_status.getText());
                pst.setString(15,txt_job.getText());
                pst.setString(16,txt_apt.getText());
                pst.setString(17,txt_doj.getText());
                
               
                

                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
        try{
           String sq = "select * from Staff_information where (id) NOT IN (select id from users)";
           pst = conn.prepareStatement(sq);
           rs = pst.executeQuery();
           
           
           while(rs.next()){
           String add1 = rs.getString("id");
           String add2 = rs.getString("first_name");
           String add3 = rs.getString("Dob");
           String result = add3.replace("/", "");
           String add4 = rs.getString("Department");
           
           String sql= "insert into users(division , username , password , emp_id) Values ('" +add4+ "' , '" +add2+ "' , '" +result+ "' , '" +add1+ "')";
           
           pst = conn.prepareStatement(sql);
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null,"User account has been successfully created :"+ "username: "+add2+"passwors"+result);
           
           
           
           }}catch(Exception e){
           
           
             JOptionPane.showMessageDialog(null,e);
           
           }
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          finally {
    try {
        if (rs != null) {
            rs.close();
        }
        if (pst != null) {
            pst.close();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
} }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
        
        
        
        
        
        
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        
         gender = "Female";
        r_male.setSelected(false);
        r_female.setSelected(true);
        
        
    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         txt_search.setText("");
          txt_id.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_contact.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_add1.setText("");
        txt_dep.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_add2.setText("");
        txt_pc.setText("");
        txt_job.setText("");
        txt_apt.setText("");
        txt_doj.setText("");
        txt_design.setText("");
        r_male.setSelected(false);
        r_female.setSelected(false);
        img.setIcon(null);
      
//        img.setIcon(null);

        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser =  new  JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        
        
        
        try {
        File image = new File(filename);
        FileInputStream fix = new FileInputStream(image);
        ByteArrayOutputStream bos = new   ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        
        for(int number;(number = fix.read(buf))!=-1;){
        
            bos.write(buf, 0, number);
            person_image = bos.toByteArray();
     
        }   
        
        }catch(Exception e ){
        
        JOptionPane.showConfirmDialog(null, e);
        
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        try{

            String sql ="select * from Staff_information where id=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
                String add1 =rs.getString("id");
                txt_id.setText(add1);

                String add2 =rs.getString("first_name");
                txt_firstname.setText(add2);

                String add3 =rs.getString("last_name");
                txt_lastname.setText(add3);

                String add4 =rs.getString("Dob");
                txt_dob.setText(add4);

                String add5 =rs.getString("Email");
                txt_email.setText(add5);

                String add6 =rs.getString("Telephone");
                txt_contact.setText(add6);

                String add7 =rs.getString("Address");
                txt_add1.setText(add7);

                String add8 =rs.getString("Department");
                txt_dep.setText(add8);
                
                String add10 =rs.getString("Salary");
                txt_salary.setText(add10);

                String add11 =rs.getString("Address2");
                txt_add2.setText(add11);
                
                String add12 =rs.getString("Apartment");
                txt_apt.setText(add12);
                
                String add13 =rs.getString("Post_code");
                txt_pc.setText(add13);
                
                String add14 =rs.getString("Status");
                txt_status.setText(add14);
                
                String add15 =rs.getString("Date_hired");
                txt_doj.setText(add15);
                
                String add16 =rs.getString("job_title");
                txt_job.setText(add16);
                
                String add17 =rs.getString("Designation");
                txt_design.setText(add17);
                
                
                String add18 = rs.getString("gender");
                if(add18.equals("Male")){
                r_male.setSelected(true);
                r_female.setSelected(false);
              }else 
                {r_female.setSelected(true);
                 r_male.setSelected(false);
                }
          
byte[] image = rs.getBytes("Image"); // ensure column name matches exactly

if (image != null && image.length > 0) {
    ImageIcon imageIcon = new ImageIcon(image);
    Image scaledImage = imageIcon.getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
    img.setIcon(new ImageIcon(scaledImage));
    img.setText(""); // clear any placeholder text
} else {
    img.setIcon(null);         // clear any existing image
    img.setText("No Image");   // show 'No Image' text
}
                
                
//                byte[] image = rs.getBytes("Image");
//                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH));
//                img.setIcon(imageIcon);

        }catch(Exception e){
          
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
         }

        
        
        
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","delete Record",JOptionPane.YES_NO_OPTION);
        if(x==0){
         try{
                String sql ="delete from Staff_information where id=? ";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_id.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try {
String val16 = txt_id.getText();
int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?", "Update Record", JOptionPane.YES_NO_OPTION);
if (x == 0) {

    // Collect form values
    String val = txt_firstname.getText();
    String val2 = txt_lastname.getText();
    String val3 = txt_dob.getText();
    String val4 = txt_contact.getText();
    String val5 = txt_email.getText();
    String val6 = txt_add1.getText();
    String val7 = txt_dep.getText();
    String val8 = txt_salary.getText();
    String val9 = txt_add2.getText();
    String val10 = txt_apt.getText();
    String val11 = txt_pc.getText();
    String val12 = txt_status.getText();
    String val13 = txt_doj.getText();
    String val14 = txt_job.getText();
    String val15 = txt_design.getText();
    String gender = r_male.isSelected() ? "Male" : (r_female.isSelected() ? "Female" : null);

    byte[] image = null;
    if (filename != null && !filename.trim().isEmpty()) {
        File file = new File(filename);
        try (FileInputStream fis = new FileInputStream(file)) {
            image = new byte[(int) file.length()];
            fis.read(image);
        }
    }

    // Update SQL statement with placeholders
    String sql = "UPDATE Staff_information SET "
            + "first_name=?, last_name=?, Dob=?, Email=?, Telephone=?, "
            + "Address=?, Department=?, Address2=?, Apartment=?, Post_code=?, "
            + "Designation=?, Status=?, Salary=?, job_title=?, Date_Hired=?, "
            + "Gender=?, Image=? "
            + "WHERE id=?";

    pst = conn.prepareStatement(sql);

    pst.setString(1, val);
    pst.setString(2, val2);
    pst.setString(3, val3);
    pst.setString(4, val5);
    pst.setString(5, val4);
    pst.setString(6, val6);
    pst.setString(7, val7);
    pst.setString(8, val9);
    pst.setString(9, val10);
    pst.setString(10, val11);
    pst.setString(11, val15);
    pst.setString(12, val12);
    pst.setString(13, val8);
    pst.setString(14, val14);
    pst.setString(15, val13);
    pst.setString(16, gender);
    pst.setBytes(17, image); // null is allowed if no new image selected
    pst.setString(18, val16);

    pst.executeUpdate();
    pst.close();

    JOptionPane.showMessageDialog(null, "Record Updated Successfully");
}
} catch (HeadlessException | IOException | SQLException e) {
JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
} finally {
try {
if (rs != null) rs.close();
if (pst != null) pst.close();
} catch (SQLException e) {
// Ignore errors on cleanup
}
}
//          String val16 = txt_id.getText();
//         int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
//        if(x==0){
//        try{
//        String val = txt_firstname.getText();
//        String val2 =txt_lastname.getText();
//        String val3 =txt_dob.getText();
//        String val4 =txt_contact.getText();
//        String val5 = txt_email.getText();
//        String val6 =txt_add1.getText();
//        String val7 =txt_dep.getText();
//        String val8 = txt_salary.getText();
//        String val9 =txt_add2.getText();
//        String val10 = txt_apt.getText();
//        String val11 =txt_pc.getText();
//        String val12 =txt_status.getText();
//        String val13 =txt_doj.getText();
//        String val14 =txt_job.getText();
//        String val15 =txt_design.getText();
//       
//      
//        
//     
//        String gender = r_male.isSelected() ? "Male" : (r_female.isSelected() ? "Female" : null);  
//        
//        
//        String sql = "UPDATE Staff_information SET "
//    + "id='" + val16 + "', "
//    + "first_name='" + val + "', "
//    + "last_name='" + val2 + "', "
//    + "Dob='" + val3 + "', "
//    + "Email='" + val5 + "', "
//    + "Telephone='" + val4 + "', "
//    + "Address='" + val6 + "', "
//    + "Department='" + val7 + "', "
//    + "Address2='" + val9 + "', "
//    + "Apartment='" + val10 + "', "
//    + "Post_code='" + val11 + "', "
//    + "Designation='" + val15 + "', "
//    + "Status='" + val12 + "', "
//    + "Salary='" + val8 + "', "
//    + "job_title='" + val14 + "', "
//    + "Date_Hired='" + val13 + "' "
//    +"Gender = '"+gender+"'"
//    + "Image = ?,"            
//    + "WHERE id='" + val16 + "'" ;
//    
//    
//
//                pst=conn.prepareStatement(sql);
//                pst.execute();
//                JOptionPane.showMessageDialog(null, "Record Updated");
//        }catch(HeadlessException | SQLException e){
//        JOptionPane.showMessageDialog(null,e);
//        }
//         try{
//             
//             
//             if (filename != null && !filename.trim().isEmpty()){
//                File file = new File(filename);
//                byte[] image;
//            try (FileInputStream fis = new FileInputStream(file)) {
//                image = new byte[(int) file.length()];
//                fis.read(image);
//            }
//            
//            String sql = "update Staff_information SET Image =? and Gender = ? where id ='"+val16+"'";
//            
//            
//            pst = conn.prepareStatement(sql);
//            pst.setBytes(1, image);
//            pst.setString(2, val16);
//            pst.setString(3, gender);
//            pst.executeUpdate();
//            pst.close();}
//        }catch(IOException | SQLException e){
//           JOptionPane.showMessageDialog(null,e); }
//        finally{
//        
//         try{
//        
//        rs.close();
//        pst.close();
//        
//        }catch(Exception e){
//     
//        }
//        
//        }
//        
//        
//        
//        
//        
//        
//        
//        
//        
//        }
//        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_add1;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_apt;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_design;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables

private ImageIcon format = null;
String filename = null;
byte[] person_image = null;
 

}
